### ISSUE TITLE
Interface the temperature and humidity sensor with BBB

### ISSUE THREAD

**Issue by Anshul-99** [cu-ecen-aeld/finalproject-vishal-anshul-shared#1]
Assignee: Anshul Somani

1. DoD: 
- [x]  Test the working of i2c-tools using a logic analyzer
Blocker resolved:
Arranging a logic analyzer
Fallback:
Directly test with the sensor 

2. DoD:
- [x] Write code, makefile and any modifications to kernel image to interface the Si7021 Sensor

3. DoD:
- [x] Test the working of the sensor

4. DoD: 

- [x] Develop patch to enable I2C-1 and I2C-2 bus on BeageleBone Black

**Comment by Anshul-99** [comment]
#Update 1

I'm facing a few issues in integratingSi7021 ( temperature and humidity sensor) with BBB via I2C.  After connecting the sensor to i2c-2, when I run `i2cdetect -r -y 2` the sensor isn't detected at all. The Si7021 has a 7-bit address of 0x40 but the board doesn't detect the sensor there.  

1. I tried using the other sensor we are using in this project, and the result was the same. 
2. I read that the bus number assigned by Linux and the bus number assigned in the datasheet don't match. So, I tried using the other available i2c bus (i2c-0). Turns out it is connected onboard to other devices. In conclusion, the i2c-2 in /dev is the i2c2 bus present in the datasheet. I have not added the patch to support i2c-1, so I didn't test it. 
3. I tried using the same image on a different board and even used different jumper cables but the issue still persisted. 
4. I then checked the output on i2c-2 bus using a logic analyzer when running `i2cdetect -r -y 2` but both SCL and SDA were in idle. There was no clock pulse on SCL. 
5. In the end I booted into the default Debian image on BBB and then ran `i2cdetect -r -y 2` while connecting the i2c2 bus to the logic analyzer. I got output on the bus. Thus, I think the issue is something related to the hardware. During this entire process I didn't use a pull-up resistor since I didn't have the right value with me. I think that might be the issue. I'm planning on using [this](https://stackoverflow.com/questions/45561359/how-to-work-in-beaglebone-black-i2c2-using-buidroot) as a reference to enable the onboard pull-up resistors and then see if it works or not

**Comment by Anshul-99** [comment]
#Update 2

Turns out the code [in](https://stackoverflow.com/questions/45561359/how-to-work-in-beaglebone-black-i2c2-using-buidroot) is the same as the code for I2C-1 patch. 

The patch tries to modify [this](https://github.com/beagleboard/linux/blob/4.19.79-ti-r30/arch/arm/boot/dts/am335x-bone-common.dtsi) file. I went through the file and it turns out I2C-2 is configured to work with pull-up resistors. My initial guess was that the lack of pull-up resistors was causing the issue. 

On further discussion with professor, he suggested that I try using the I2C-1 [patch](https://github.com/cu-ecen-aeld/final-project-madhukararora/blob/master/base_external/patches/linux/i2c1.patch#L18). When I tried it there I got an error on `make linux-patch` saying that the patch failed. The reason for this error is that the dtsi file was modified and the patch doesn't work directly for it. The patch will have to generated again using `git diff`. 

I'll try implementing the I2C-1 patch to resolve the problem.

**Comment by Anshul-99** [comment]
#Update 3

Assignee: Anshul Somani

No blockers:

Commit: [e6a75526d3d2aa235a9211b987d06240454fa72a](https://github.com/cu-ecen-aeld/finalproject-vishal-anshul-shared/blob/master/sensors/temp_humidity.c)

1. Added patch for I2C-1 and `i2cdetect -r -y 1` detects Si7021 sensor at the right address. 

2. Developed code to test the sensor and then added it to final-project package in buildroot.

**Comment by Anshul-99** [comment]
#Update 4
![temp_humidity](https://user-images.githubusercontent.com/69078393/162669564-9a0a8928-1a03-47df-9e31-14ce1b05170f.JPG)
![Temp_Sensor](https://user-images.githubusercontent.com/69078393/162669566-a89b9057-2e5f-47b8-878e-80a3c615dc66.JPG)

No Blockers
Assignee: Anshul Somani
commit: [204153c5409c4af4fd123975cb86a422d4779b87](https://github.com/cu-ecen-aeld/finalproject-vishal-anshul-shared/tree/204153c5409c4af4fd123975cb86a422d4779b87)

Working of the temperature and humidity sensor tested.

**Comment by Anshul-99** [comment]
#Update 5

This wasn't originally a part of this issue. I'm just adding it here because it is relevant to this issue. 

Assignee: Anshul Somani
No Blockers

commit: [9fa21439a75414d2fd009c03d313344ad2ebb7b3](https://github.com/cu-ecen-aeld/final-project-Anshul-99/tree/9fa21439a75414d2fd009c03d313344ad2ebb7b3)

[patch](https://github.com/cu-ecen-aeld/final-project-Anshul-99/blob/9fa21439a75414d2fd009c03d313344ad2ebb7b3/base_external/patches/linux/i2c1.patch)

Due to some change in am335x-bone-common.dtsi [link](https://github.com/beagleboard/linux/blob/4.19.79-ti-r30/arch/arm/boot/dts/am335x-bone-common.dtsi) the initial [patch](https://github.com/cu-ecen-aeld/final-project-madhukararora/blob/master/base_external/patches/linux/i2c1.patch#L18) didn't work anymore. It resulted in an error on calling `make linux-patch`. To resolve this a new patch was generated to enable both I2C-1 and I2C-2 buses. 

To generate the patch, the original file (am335x-bone-common.dtsi) was pushed to github. Then the same file was modified by adding the contents of the patch. To enable I2C-1 and configure the pins used for I2C-2 bus. Then `git diff` was used to generate the patch file. 

I connected the sensor to I2C-1 and then I2C-2 bus. I then tested the patch file using  `i2cdetect -r -y 1` and `i2cdetect -r -y 2` commands to check if the board could detect Si7021 sensor. The test was successful and the board detected the sensor on both the buses.

**Comment by swatikadivar** [comment]
> Assignee: Anshul Somani

update assignee on right-hand upper corner of this page.
